### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by ycdhqzhiai** [mndar/facenet_classifier#1]
hi;
@mndar Which version of tensorflow and bazel are you using?

**Comment by mndar** [comment]
Bazel 0.6.0 installed using bazel-0.6.0-installer-linux-x86_64.sh
TensorFlow 1.3.0

**Comment by ycdhqzhiai** [comment]
@mndar 
hi, I use bazel 0.61 to compile tensorflow1.3, There have been some mistakes when I built facenet_classifier
![1](https://user-images.githubusercontent.com/12273405/32153221-2472647c-bd64-11e7-9311-d44bb37171bd.jpg)
I made some changes to makefile
![image](https://user-images.githubusercontent.com/12273405/32153258-540ff596-bd64-11e7-8d9a-09943addd4be.png)
can you help me?thanks

**Comment by ycdhqzhiai** [comment]
@mndar 
hi, I compiled tensorflow1.3 with bazel0.6.1,there have been some mistakes when I built facenet_classifier
![1](https://user-images.githubusercontent.com/12273405/32153626-b4f4aa3a-bd66-11e7-85f7-bbb4cc13d629.jpg)
makefile have been changed
![1](https://user-images.githubusercontent.com/12273405/32153648-d6544ca8-bd66-11e7-9e4e-69521394fb2e.jpg)

I don't know how to solve it.Can you help me?thanks.

**Comment by mndar** [comment]
I've never got this error. I am not sure what is causing this compile error.
Did my Makefile with -I/usr/lib/python2.7/site-packages/tensorflow/include/external/nsync/public/ not work for you?

**Comment by ycdhqzhiai** [comment]
yes, it's not work for me.I'm not sure missing someting.I just compile TF1.3 step by step with bazel as given here http://tuatini.me/building-tensorflow-as-a-standalone-project/ ?

**Comment by mndar** [comment]
What's the error you get with my Makefile?

**Comment by ycdhqzhiai** [comment]
get the same error.

**Comment by mndar** [comment]
I'll have to try compiling on Ubuntu to help you further.

**Comment by ycdhqzhiai** [comment]
thank you!!!

**Comment by ycdhqzhiai** [comment]
@mndar i am sorry to disturb you again.I've compiled classify successfully when I use c++11, I don't know why C++11 doesn't work in your makefile.
..now I want to use the input video camera to get 128 dimensional feature.like this:
`cap>>img;
       faceCascade.detectMultiScale(img, faces, 1.2, 6, 0, cv::Size(160, 160));  

       if(faces.size()>0)
       {
          for(int i =0; i<faces.size(); i++)
          {
              rectangle(img, Point(faces[i].x, faces[i].y), Point(faces[i].x + faces[i].width, faces[i].y + faces[i].height),
                              Scalar(0, 255, 0), 1, 8);    
                roi_img=img(Rect(faces[i].x, faces[i].y, faces[i].width, faces[i].height));
                resize(roi_img,des,cv::Size(160,160),0,0,CV_INTER_LINEAR);
          }
       }
        classifier.video(des);
        //classifier.parse_images_path (images_path, 0);
        //classifier.create_input_tensor ();
        classifier.create_phase_tensor ();
        //classifier.run();
        classifier.video_run();`


`void FacenetClassifier::video(Mat img) {
        Tensor input_tensor(DT_FLOAT, TensorShape({1, 160, 160, 3}));
        // get pointer to memory for that Tensor
        float *p = input_tensor.flat<float>().data();
        Mat camera_image(160 , 160, CV_32FC3, p);
        cout << "yuan shi tu pian" << endl;
        img.convertTo(camera_image, CV_32FC3);
        cout << input_tensor.DebugString() << endl;
        this->input_tensor = input_tensor;
`
`void FacenetClassifier::video_run() {
        string input_layer = "input:0";
        string phase_train_layer = "phase_train:0";
        string output_layer = "embeddings:0";
        std::vector<tensorflow::Tensor> outputs;
        std::vector<std::pair<string, tensorflow::Tensor>> feed_dict = {
                  {input_layer, input_tensor},
                  {phase_train_layer, phase_tensor},
        };
        //cout << "Input Tensor: " << input_tensor.DebugString() << endl;
        Status run_status = session->Run(feed_dict, {output_layer}, {} , &outputs);
        if (!run_status.ok()) {
                  LOG(ERROR) << "Running model failed: " << run_status << "\n";
                  return;
        }
        cout << "Output: " << outputs[0].DebugString() << endl;

        float *p = outputs[0].flat<float>().data();
        Mat output_mat;
        Mat mat_row (cv::Size (128, 1), CV_32F, p, Mat::AUTO_STEP);
        Mat mat_row_float, mat_tensor_reshaped;
        mat_row.convertTo (mat_row_float, CV_32FC3);
        //mat_tensor_reshaped = mat_row_float.reshape (0,1);
        //mat_training_tensors.push_back (mat_tensor_reshaped);
        output_mat = mat_row;
        this->output_mat = output_mat;
        cout << output_mat <<endl;

}`

i want to get out_mat.But I find that no matter who the face will get the same results, even img is empty

**Comment by ycdhqzhiai** [comment]
hi @mndar II've successfully compiled classify when I use c++11,and I don't know why c++11 does not work in your makefile.....
now I want to get the output_mat when the input is the camera video.like this;

       while(c!=27){
             cap>>img;
             faceCascade.detectMultiScale(img, faces, 1.2, 6, 0, cv::Size(160, 160)); 

             if(faces.size()>0)
             {
                   for(int i =0; i<faces.size(); i++)
                   {
                         rectangle(img, Point(faces[i].x, faces[i].y), Point(faces[i].x + faces[i].width, faces[i].y + faces[i].height),
                              Scalar(0, 255, 0), 1, 8);
                          roi_img=img(Rect(faces[i].x, faces[i].y, faces[i].width, faces[i].height));
                          resize(roi_img,des,cv::Size(160,160),0,0,CV_INTER_LINEAR);
                   }
               classifier.video(des);
               //classifier.parse_images_path (images_path, 0);
              //classifier.create_input_tensor ();
              classifier.create_phase_tensor ();
               //classifier.run();
              classifier.video_run();
              imshow("Camera", des);
              c = waitKey(1);
             }
      }
Function
  
    void FacenetClassifier::video(Mat img) {
        Tensor input_tensor(DT_FLOAT, TensorShape({1, 160, 160, 3}));
        // get pointer to memory for that Tensor
        float *p = input_tensor.flat<float>().data();
        Mat camera_image(160 , 160, CV_32FC3, p);
        cout << "yuan shi tu pian" << endl;
        img.convertTo(camera_image, CV_32FC3);
        cout << input_tensor.DebugString() << endl;
        this->input_tensor = input_tensor;
     }
    void FacenetClassifier::video_run() {
        string input_layer = "input:0";
        string phase_train_layer = "phase_train:0";
        string output_layer = "embeddings:0";
        std::vector<tensorflow::Tensor> outputs;
        std::vector<std::pair<string, tensorflow::Tensor>> feed_dict = {
                  {input_layer, input_tensor},
                  {phase_train_layer, phase_tensor},
        };
        //cout << "Input Tensor: " << input_tensor.DebugString() << endl;
        Status run_status = session->Run(feed_dict, {output_layer}, {} , &outputs);
        if (!run_status.ok()) {
                  LOG(ERROR) << "Running model failed: " << run_status << "\n";
                  return;
        }
        cout << "Output: " << outputs[0].DebugString() << endl;

        float *p = outputs[0].flat<float>().data();
        Mat output_mat;
        Mat mat_row (cv::Size (128, 1), CV_32F, p, Mat::AUTO_STEP);
        Mat mat_row_float, mat_tensor_reshaped;
        mat_row.convertTo (mat_row_float, CV_32FC3);
        //mat_tensor_reshaped = mat_row_float.reshape (0,1);
        //mat_training_tensors.push_back (mat_tensor_reshaped);
        output_mat = mat_row;
        this->output_mat = output_mat;
        cout << output_mat <<endl;
    }
But I find no matter who face even the img is empty, output_mat is the same.
However, using JPG picture input can get the correct features.like this:

        model_path = string (argv[1]);
	images_path = string (argv[2]);
	FacenetClassifier classifier = FacenetClassifier (model_path);
	classifier.parse_images_path (images_path, 0);
	classifier.create_input_tensor ();
	classifier.create_phase_tensor ();
	classifier.run ();

./classify ../model/20170512-110547.pb ../data/

**Comment by mndar** [comment]
Try feeding Facenet more than one face (an additional dummy Mat if you have
just 1 face detected) and try using the model generated from the
CASIA-WebFace dataset 20170511-185253. Download it from
https://github.com/davidsandberg/facenet
