### ISSUE TITLE
Getting very bad results

### ISSUE THREAD

**Issue by sayanmutd** [mndar/facenet_classifier#10]
Tried to train a KNN based classifier based on the VGGFace2 weight found in facenet Github page. But the results are biased towards one class. @mndar  Could you please tell which weights files are you using and the number of training samples in each class.

**Comment by mndar** [comment]
I am using an old model, 20180402-114759.pb 
I think for this program I'm using 5-6 images per class.
But this concept has been tested for upto 2000 people in the Casia-WebFace database,

Which library are you using to extract faces? OpenCV, DLib?

**Comment by sayanmutd** [comment]
Can you please share the weight files. I have used the MS Celeb 1-M sample datatset [Dataset](https://www.msceleb.org/download/sampleset) which contains the Sample FaceAligned Data. But i getting very bad results. How can you help me to reproduce the results that you are getting @mndar

**Comment by mndar** [comment]
From your database, you first need to extract faces of and resize them to size 160x160
Are you currently doing that?

**Comment by sayanmutd** [comment]
No, i haven't resized the images. But, is it so that without resizing the results get affected heavily?

**Comment by mndar** [comment]
The results will be gibberish without you supplying correct input in the form of 160x160 faces extracted suing a library like OpenCV or DLib.

**Comment by sayanmutd** [comment]
@mndar  It works well after the images are resized. Thank you!!
