### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by delongqilinksprite** [mndar/facenet_classifier#3]
Hi ,
I downloaded the project,my environment: ubuntu16.04, opencv3.3.1,tensorflow1.4.0,got an error as below:
/usr/local/include/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory

thanks!

**Comment by mndar** [comment]
Hello,
Did you install Eigen as described on this page?
http://tuatini.me/building-tensorflow-as-a-standalone-project/

Regards
Mandar Joshi

**Comment by delongqilinksprite** [comment]
thanks a lot,I got it!
